### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by sbdchd**
Fixed some spelling issues and adjusted the formatting.

### CODE REVIEW

**Comment by tleyden** [comment]
Thanks for this!  Just a heads up though, we can't take PR's through this repository, they must be done via Gerrit reviews.  And unfortunately, we don't have any instructions up on how to do this.  I'll see what I can do to fix this situation, you aren't the first community user to get bitten by this.

@brett19 Hey I saw you had converted a few github PR's to Gerrit reviews.  Do you have a slick way of doing this with the push of a button or did you just do it "by hand"?

**Comment by tleyden** [comment]
@sbdchd Can you register with our Review Site (http://review.couchbase.org) and accept our CLA?  If you are already registered, ensure your Git Email is attached to your Gerrit Profile.

Sorry about the hassle..

**Comment by sbdchd** [comment]
I registered with Gerrit but do I need to do anything else?

Btw, Gerrit doesn't recognize `.xyz` email addresses as valid, which is the TLD that I use for my default address on github.

**Comment by tleyden** [comment]
@sbdchd nope, you're good!  The ball is in our court now.  @maniktaneja I will email you the internal wiki page that @brett19 sent me.

**Pull request closed without merging**
