### PR TITLE
Adding wrapper for memcached decrement function

### PR DESCRIPTION
**Pull request by jclinford**
Adding decrement support to go-couchbase.

NOTE: This PR relies on functionality in https://github.com/couchbase/gomemcached/pull/2

### CODE REVIEW

**Comment by tleyden** [comment]
See [this comment](https://github.com/couchbase/go-couchbase/pull/65#issuecomment-140156926) -- the same applies for this PR.

**Comment by tleyden** [comment]
@jclinford Can you register with our Review Site (http://review.couchbase.org) and accept our CLA?  If you are already registered, ensure your Git Email is attached to your Gerrit Profile.

Sorry about the hassle..

**Comment by jclinford** [comment]
No worries! I registered with gerrit, thanks for the instructions

**Comment by tleyden** [comment]
@maniktaneja can you take a look at this PR?  Looks like a straightforward and useful addition.

**Comment by maniktaneja** [comment]
Merged via couchbase@3b77a41

Thanks for your contribution. Next time you want to push commits to go-couchbase please do so via gerrit.

**Pull request closed without merging**
