### PR TITLE
Modified go get README because new URL doesn't work

### PR DESCRIPTION
**Pull request by tehmoon**
I've got that weird error when I use github.com/couchbase/go-couchbase as couchbase package:
```shell
github.com/couchbase/go-couchbase/conn_pool.go:56: conn.SetKeepAliveOptions undefined (type *memcached.Client has no field or method SetKeepAliveOptions)
```
I am using now github.com/couchbaselabs/go-couchbase in all my projects and it works better.

Let me now what you think

### CODE REVIEW

**Comment by maniktaneja** [comment]
You need to update your version of go. We have currently tested this with go1.3.3

**Comment by tehmoon** [comment]
Hi thank you for the answer.
I'm currently on :
```shell
$>go version
go version go1.4.2 linux/amd64
```

**Comment by maniktaneja** [comment]
Not sure what the issue is. Perhaps you could try cleaning out the repos and the go get ./... 

couchblaselabs/go-couchbase is pretty much depreciated. All future enhancements and bug fixes will go into this repo.

**Comment by tehmoon** [comment]
Oh that did the trick !

One time I had to get the wrong couchbaselabs repo which corrupted me the good couchbase/go-couchbase so I assumed the good one didn't work and used the bad one in all my projects.

I'm so sorry for the waste of time, I didn't think to clean the dirs and try again with the good url.

Anyway many thanks :)

**Pull request closed without merging**
